### ISSUE TITLE
your code doesn't really do anything

### ISSUE THREAD

**Issue by jpskycak** [skycakjustin/assignment-problems#1]
in naming_convention_example.py, your code doesn't actually accomplish anything. I think it's old code; if it is, then you should get rid of it

**Comment by skycakjustin** [comment]
But I thought it might be useful later, for some reaons

**Comment by jpskycak** [comment]
Can you think of a specific reason? If not, at least move it to a folder of old code to keep it separate from the rest of your library

**Comment by skycakjustin** [comment]
ok, good idea
